import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Example values for demo; replace with real user/order info in your app
  const demoOrderId = `ORDER_DEMO_${Date.now()}`;
  const demoAmount = "100.00";
  const demoCustomerId = "demo_user";
  const demoEmail = "demo@example.com";
  const demoMobile = "9999999999";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            display: "flex",
            gap: 16,
            padding: 16,
            background: "#f5f5f5",
          }}
        >
          <Link href="/">
            <button>Home</button>
          </Link>
          <Link href="/admin">
            <button>Admin Dashboard</button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
